Publish Kubernetes CVEs: CVE-2020-{8554,8567,8568,8569,8570}
kubernetes-security/cvelist-public pull request #1
Opened 2021-01-12 01:24 UTC by tallclair

2021-01-12 02:52 UTC, ritazh approved these changes
CVE-2020-8567 and CVE-2020-8568 LGTM

2021-01-12 17:06 UTC, aramase commented on 2020/8xxx/CVE-2020-8568.json
> +        "DATE_PUBLIC": "2020-11-16T21:00:00.000Z",
Date public for this CVE is `2020-11-10T21:00:00.000Z`

2021-01-12 18:39 UTC, joelsmith requested changes
Per https://github.com/kubernetes/security/blob/master/cna-handbook.md#populate-cve-details we should begin the title and descriptions with Kubernetes <component>. I have provided suggested rewording which you can use or ignore, but I think that it's important to mention Kubernetes so that it will be clear what is affected in global CVE lists.

2021-01-15 18:28 UTC, tallclair commented
Thanks Joel! All feedback integrated. I'll merge & open the upstream PR

2021-01-15 18:29 UTC, merged